USE [master]
GO

/****** Object:  Database [commentor]    Script Date: 6/11/2015 3:21:38 PM ******/
DROP DATABASE [commentor]
GO

/****** Object:  Database [commentor]    Script Date: 6/11/2015 3:21:38 PM ******/
CREATE DATABASE [commentor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'commentor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\commentor.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'commentor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\commentor_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [commentor] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [commentor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [commentor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [commentor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [commentor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [commentor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [commentor] SET ARITHABORT OFF 
GO

ALTER DATABASE [commentor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [commentor] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [commentor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [commentor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [commentor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [commentor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [commentor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [commentor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [commentor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [commentor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [commentor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [commentor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [commentor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [commentor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [commentor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [commentor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [commentor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [commentor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [commentor] SET RECOVERY FULL 
GO

ALTER DATABASE [commentor] SET  MULTI_USER 
GO

ALTER DATABASE [commentor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [commentor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [commentor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [commentor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [commentor] SET  READ_WRITE 
GO

